version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - godot        # enforces full sentences in comments
    - misspell
    - bodyclose
    - noctx
    - unconvert
    - unparam

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment   # not worth the complexity for this project
    errcheck:
      check-type-assertions: true
    staticcheck:
      checks: ["all"]
    misspell:
      locale: US

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck
          - godot
          - unparam
      - path: "internal/rules/"
        linters:
          - godot     # rule descriptions intentionally lack trailing periods in some places

formatters:
  enable:
    - gofmt
